export const instituteList = [
  "University of Toronto",
  "University of Waterloo",
  "University of British Columbia",
  "McGill University",
  "University of Alberta",
  "University of Calgary",
  "Western University",
  "Queen's University",
  "University of Ottawa",
  "University of Manitoba",
  "Dalhousie University",
  "Simon Fraser University",
  "University of Victoria",
  "York University",
  "University of Saskatchewan",
  "University of Guelph",
  "Carleton University",
  "University of Regina",
  "University of Windsor",
  "University of Lethbridge",
  "Memorial University of Newfoundland",
  "Lakehead University",
  "Ryerson University",
  "Acadia University",
  "University of New Brunswick",
  "University of Prince Edward Island",
  "Brock University",
  "University of Ontario Institute of Technology",
  "Wilfrid Laurier University",
  "University of the Fraser Valley",
  "University of Winnipeg",
  "Mount Allison University",
  "University of Northern British Columbia",
  "Ho Chi Minh City University of Technology",
  "Ho Chi Minh City University of Science",
  "Ho Chi Minh City University of Social Sciences and Humanities",
  "Ho Chi Minh City University of Economics",
  "Ho Chi Minh City University of Law",
  "Ho Chi Minh City University of Foreign Languages and Information Technology",
  "Ho Chi Minh City University of Pedagogy",
  "Ho Chi Minh City University of Architecture",
  "Ho Chi Minh City University of Agriculture and Forestry",
  "Ho Chi Minh City University of Transport",
  "Ho Chi Minh City University of Technical Education",
  "Ho Chi Minh City University of Industry",
];