export { handleAnswerChange } from "./answerChange"
export { handleExitQuiz } from "./exitQuiz"
export { handleQuestionChange } from "./questionChange"
export { handleUpdateModal } from "./modalUpdate"
export { handleCloseModal } from "./modalClose"
export { handleCorrectAnswerChange } from "./correctAnswerChange"
export { handleQuestionCardClick} from "./questionCardClick"
export { handleCreateQuestion } from "./questionCreate"
export { handleDeleteQuestion } from "./questionDelete"
export { handleSaveQuiz } from "./saveQuiz"
export { handleQuizDetailChange } from "./quizDetailChange"
export { handeDuplicateQuestion } from "./questionDuplicate"
export { handleMessageErrors } from "./handleErrors"

